[build]
builder = "dockerfile"
dockerfilePath = "vula_mind/Dockerfile"
buildContext = "vula_mind"

[deploy]
healthcheckPath = "/status"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[volumes]]
mountPath = "/data"
