"""Seams between the tap service and the outside world (DB, WhatsApp, payment gateway).

Production implementations: `repo.SupabaseRepo`, `adapters.WhatsAppMessenger`,
`adapters.PayFastGateway`. Tests use in-memory fakes, so no test touches Meta, PayFast or Supabase.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Optional, Protocol, Sequence


class Repo(Protocol):
    # tags / tokens
    def get_tag_by_code(self, code: str) -> Optional[dict]: ...
    def get_tag(self, tenant_id: str, tag_id: str) -> Optional[dict]: ...
    def create_claim_token(self, *, tenant_id: str, tag_id: str, token_hash: str,
                           expires_at: datetime) -> None: ...
    def consume_claim_token(self, token_hash: str, now: datetime) -> Optional[dict]: ...
    # bills
    def live_bills_for_tag(self, tenant_id: str, tag_id: str) -> list[dict]: ...
    def get_bill(self, tenant_id: str, bill_id: str) -> Optional[dict]: ...
    def create_bill(self, row: dict) -> dict: ...
    def cas_bill(self, tenant_id: str, bill_id: str, *, expected: str, new: str,
                 fields: Optional[dict] = None) -> bool: ...
    def update_bill(self, tenant_id: str, bill_id: str, fields: dict) -> None: ...
    # sessions
    def create_session(self, row: dict) -> dict: ...
    def get_session(self, tenant_id: str, session_id: str) -> Optional[dict]: ...
    def get_session_any_tenant(self, session_id: str) -> Optional[dict]: ...
    def active_session_for_payer(self, tenant_id: str, payer_hash: str,
                                 now: datetime) -> Optional[dict]: ...
    def cas_session(self, tenant_id: str, session_id: str, *, expected: str, new: str,
                    fields: Optional[dict] = None) -> bool: ...
    # money
    def record_event(self, *, tenant_id: Optional[str], source: str, event_id: str) -> bool: ...
    def record_payment(self, row: dict) -> Optional[dict]: ...
    def insert_ledger_lines(self, rows: Sequence[dict]) -> None: ...
    def get_split_rule(self, tenant_id: str, staff_id: Optional[str]) -> Optional[dict]: ...
    # setup / admin
    def get_settings(self, tenant_id: str) -> Optional[dict]: ...
    def upsert_settings(self, tenant_id: str, fields: dict) -> None: ...
    def list_tags(self, tenant_id: str) -> list[dict]: ...
    def create_tag(self, row: dict) -> dict: ...
    def update_tag(self, tenant_id: str, tag_id: str, fields: dict) -> None: ...
    def recent_bills(self, tenant_id: str, limit: int = 20) -> list[dict]: ...
    def list_split_rules(self, tenant_id: str) -> list[dict]: ...
    def upsert_split_rule(self, tenant_id: str, scope: str, fields: dict) -> None: ...
    def team_members(self, tenant_id: str) -> list[dict]: ...
    # display
    def merchant_name(self, tenant_id: str) -> str: ...
    def staff_name(self, tenant_id: str, staff_id: Optional[str]) -> Optional[str]: ...
    def tenant_wa_number(self, tenant_id: str) -> Optional[str]: ...
    def team_phones(self, tenant_id: str, staff_id: Optional[str]) -> list[str]: ...


class Messenger(Protocol):
    async def text(self, tenant_id: str, phone: str, body: str) -> bool: ...
    async def buttons(self, tenant_id: str, phone: str, body: str,
                      buttons: list[dict]) -> bool: ...
    async def list(self, tenant_id: str, phone: str, header: str, body: str, button: str,
                   rows: list[dict]) -> bool: ...


class Gateway(Protocol):
    async def create_checkout(self, *, tenant_id: str, session: dict, description: str) -> Optional[str]:
        """Return the hosted-checkout URL for this session, or None if no gateway is configured."""

    async def verify_itn(self, *, tenant_id: str, headers: dict, body: bytes, form: dict) -> Optional[dict[str, Any]]:
        """Return {'reference','paid','amount_cents','pf_payment_id','currency'?} when authentic, else None."""
