"""Seams between the tap service and the outside world (DB, WhatsApp, payment gateway).

Production implementations: `repo.SupabaseRepo`, `adapters.WhatsAppMessenger`,
`adapters.PayFastGateway`. Tests use in-memory fakes, so no test touches Meta, PayFast or Supabase.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Optional, Protocol, Sequence


class Repo(Protocol):
    # tags / tokens
    def get_tag_by_code(self, code: str) -> Optional[dict]: ...
    def get_tag(self, tenant_id: str, tag_id: str) -> Optional[dict]: ...
    def create_claim_token(self, *, tenant_id: str, tag_id: str, token_hash: str,
                           expires_at: datetime) -> None: ...
    def consume_claim_token(self, token_hash: str, now: datetime) -> Optional[dict]: ...
    # bills
    def live_bills_for_tag(self, tenant_id: str, tag_id: str) -> list[dict]: ...
    def get_bill(self, tenant_id: str, bill_id: str) -> Optional[dict]: ...
    def create_bill(self, row: dict) -> dict: ...
    def cas_bill(self, tenant_id: str, bill_id: str, *, expected: str, new: str,
                 fields: Optional[dict] = None) -> bool: ...
    def update_bill(self, tenant_id: str, bill_id: str, fields: dict) -> None: ...
    # sessions
    def create_session(self, row: dict) -> dict: ...
    def get_session(self, tenant_id: str, session_id: str) -> Optional[dict]: ...
    def get_session_any_tenant(self, session_id: str) -> Optional[dict]: ...
    def active_session_for_payer(self, tenant_id: str, payer_hash: str,
                                 now: datetime) -> Optional[dict]: ...
    def cas_session(self, tenant_id: str, session_id: str, *, expected: str, new: str,
                    fields: Optional[dict] = None) -> bool: ...
    # money
    def record_event(self, *, tenant_id: Optional[str], source: str, event_id: str) -> bool: ...
    def record_payment(self, row: dict) -> Optional[dict]: ...
    def insert_ledger_lines(self, rows: Sequence[dict]) -> None: ...
    def get_split_rule(self, tenant_id: str, staff_id: Optional[str]) -> Optional[dict]: ...
    # setup / admin
    def get_settings(self, tenant_id: str) -> Optional[dict]: ...
    def upsert_settings(self, tenant_id: str, fields: dict) -> None: ...
    def list_tags(self, tenant_id: str) -> list[dict]: ...
    def create_tag(self, row: dict) -> dict: ...
    def update_tag(self, tenant_id: str, tag_id: str, fields: dict) -> None: ...
    def recent_bills(self, tenant_id: str, limit: int = 20) -> list[dict]: ...
    def list_split_rules(self, tenant_id: str) -> list[dict]: ...
    def upsert_split_rule(self, tenant_id: str, scope: str, fields: dict) -> None: ...
    def team_members(self, tenant_id: str) -> list[dict]: ...
    # coach app (devices, enrolment, push, live updates)
    def get_member(self, tenant_id: str, member_id: str) -> Optional[dict]: ...
    def put_enrol_code(self, tenant_id: str, member_id: str, code_hash: str, expires_at: datetime,
                       created_by: str) -> None: ...
    def get_enrol_code(self, tenant_id: str, member_id: str) -> Optional[dict]: ...
    def bump_enrol_attempts(self, code_id: str) -> None: ...
    def burn_enrol_code(self, code_id: str, now_iso: str) -> None: ...
    def create_device(self, row: dict) -> dict: ...
    def get_device(self, tenant_id: str, device_id: str) -> Optional[dict]: ...
    def get_device_by_token_hash(self, token_hash: str) -> Optional[dict]: ...
    def update_device(self, tenant_id: str, device_id: str, fields: dict) -> None: ...
    def list_devices(self, tenant_id: str) -> list[dict]: ...
    def upsert_push_sub(self, row: dict) -> None: ...
    def delete_push_sub(self, endpoint: str) -> None: ...
    def push_subs_for(self, tenant_id: str, member_id: str) -> list[dict]: ...
    def bill_updates(self, tenant_id: str, since_iso: str, staff_id: Optional[str]) -> list[dict]: ...
    def paid_detail(self, tenant_id: str, bill_id: str, party_id: Optional[str]) -> dict: ...
    # receipts
    def receipt_source(self, payment_id: str) -> Optional[dict]: ...
    def revoke_receipt(self, tenant_id: str, payment_id: str) -> None: ...
    def merchant_vat(self, tenant_id: str) -> dict: ...
    # tax invoices
    def invoice_settings(self, tenant_id: str) -> Optional[dict]: ...
    def get_tax_invoice(self, tenant_id: str, payment_id: str) -> Optional[dict]: ...
    def insert_tax_invoice(self, row: dict) -> Optional[dict]: ...
    def max_tax_number(self, tenant_id: str) -> int: ...
    def latest_paid_payment(self, tenant_id: str, payer_hash: str) -> Optional[str]: ...
    def put_tax_request(self, row: dict) -> None: ...
    def open_tax_request(self, tenant_id: str, payer_hash: str, now_iso: str) -> Optional[dict]: ...
    def close_tax_request(self, request_id: str, status: str) -> None: ...
    # unpaid-bill reminders
    def stale_sessions(self, now_iso: str, limit: int = 100) -> list[dict]: ...
    def enabled_tenants(self) -> list[str]: ...
    def bills_with_status(self, tenant_id: str, status: str, limit: int = 100) -> list[dict]: ...
    def unpaid_bills(self, tenant_id: str) -> list[dict]: ...
    def reminders_for_bill(self, tenant_id: str, bill_id: str) -> list[dict]: ...
    def insert_reminder(self, row: dict) -> Optional[dict]: ...
    def update_reminder(self, reminder_id: str, fields: dict) -> None: ...
    def delete_reminder(self, reminder_id: str) -> None: ...
    def cancel_other_sessions(self, tenant_id: str, bill_id: str, keep: Optional[str]) -> None: ...
    def is_opted_out(self, tenant_id: str, phone: str) -> bool: ...
    # display
    def merchant_name(self, tenant_id: str) -> str: ...
    def staff_name(self, tenant_id: str, staff_id: Optional[str]) -> Optional[str]: ...
    def tenant_wa_number(self, tenant_id: str) -> Optional[str]: ...
    def team_phones(self, tenant_id: str, staff_id: Optional[str]) -> list[str]: ...


class Messenger(Protocol):
    async def text(self, tenant_id: str, phone: str, body: str) -> bool: ...
    async def buttons(self, tenant_id: str, phone: str, body: str,
                      buttons: list[dict]) -> bool: ...
    async def list(self, tenant_id: str, phone: str, header: str, body: str, button: str,
                   rows: list[dict]) -> bool: ...
    async def template(self, tenant_id: str, phone: str, name: str, params: list[str]) -> bool: ...
    async def document(self, tenant_id: str, phone: str, data: bytes, filename: str, caption: str) -> bool: ...
    async def link_button(self, tenant_id: str, phone: str, body: str, label: str, url: str) -> bool:
        """A message with one URL button (the address is not shown). Falls back to `body` + the plain link."""


class Gateway(Protocol):
    async def create_checkout(self, *, tenant_id: str, session: dict, description: str) -> Optional[str]:
        """Return the hosted-checkout URL for this session, or None if no gateway is configured."""

    async def verify_itn(self, *, tenant_id: str, headers: dict, body: bytes, form: dict) -> Optional[dict[str, Any]]:
        """Return {'reference','paid','amount_cents','pf_payment_id','currency'?} when authentic, else None."""


class Pusher(Protocol):
    async def send(self, sub: dict, payload: dict) -> str:
        """Deliver one Web Push. Returns 'ok', 'gone' (subscription dead — delete it) or 'error'."""
