-- ============================================================
-- Vula Group — Supabase Migration 004: Per-Tenant Yoco Accounts
-- Run AFTER migration 002 (depends on set_updated_at function)
--
-- Stores Yoco API keys per Vula Commerce tenant.
-- Populated via the "Connect Yoco" button in Vula Admin.
-- Client gets their keys from portal.yoco.com → pastes into Vula Admin.
-- ============================================================

CREATE TABLE IF NOT EXISTS vula_yoco_accounts (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           TEXT NOT NULL UNIQUE,
    company_name        TEXT,

    -- Yoco API credentials
    secret_key          TEXT NOT NULL,    -- sk_live_... or sk_test_...
    public_key          TEXT,             -- pk_live_... or pk_test_...
    webhook_secret      TEXT,             -- generated by Yoco when webhook registered

    -- Mode + status
    mode                TEXT NOT NULL DEFAULT 'live'
                            CHECK (mode IN ('live', 'test')),
    status              TEXT NOT NULL DEFAULT 'connected'
                            CHECK (status IN ('connected', 'error', 'disconnected')),
    webhook_registered  BOOLEAN NOT NULL DEFAULT FALSE,
    webhook_id          TEXT,             -- Yoco's webhook ID if auto-registered

    -- Tracking
    connected_by        TEXT,
    connected_at        TIMESTAMPTZ DEFAULT NOW(),
    last_error          TEXT,
    last_test_at        TIMESTAMPTZ,      -- last time keys were verified against Yoco API

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_yoco_accounts_tenant ON vula_yoco_accounts(tenant_id);

CREATE TRIGGER trg_yoco_accounts_updated_at
    BEFORE UPDATE ON vula_yoco_accounts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RLS: tenants can only see their own keys (admin uses service role)
ALTER TABLE vula_yoco_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON vula_yoco_accounts
    USING (tenant_id = current_setting('app.tenant_id', TRUE));
