-- 180_durable_local_stores.sql — Supabase homes for stores that lived only in local SQLite.
--
-- 2026-09-27: the Railway service has no volume attached (railway.toml declares /data, but the
-- service's volume list is empty), so everything under settings.data_dir was wiped on every
-- deploy: generated drafts, the phone → tenant/role registry, the Takeoff construction rates
-- and supplier edits, and every Takeoff job (held only in memory). Each store keeps its SQLite
-- file as a local cache and now writes through to these tables (vula/durable.py), reloading
-- from them when the local copy is empty.
-- Idempotent. RLS on everywhere; the service role (the API) is the only reader/writer.

create table if not exists vula_drafts (
    draft_id    text primary key,
    tenant_id   text not null,
    doc_type    text not null,
    brief       text not null,
    content     text not null,
    word_count  integer default 0,
    model       text,
    sources     integer default 0,
    created_at  timestamptz not null default now()
);
create index if not exists idx_vula_drafts_tenant on vula_drafts (tenant_id, created_at desc);
alter table vula_drafts enable row level security;

-- Already exists in production (created by hand); this makes a fresh database match it.
create table if not exists vula_tenant_phones (
    id          bigint generated by default as identity primary key,
    tenant_id   text not null,
    phone       text not null unique,
    label       text,
    role        text not null default 'staff',
    created_at  timestamptz default now()
);
alter table vula_tenant_phones enable row level security;

-- Platform-level scraped construction rates (not tenant data) — same columns as the SQLite
-- material_rates / scrape_log tables in vula/takeoff/construction_rates_scraper.py.
create table if not exists vula_material_rates (
    key         text primary key,
    label       text not null,
    unit        text,
    low         double precision,
    high        double precision,
    mid         double precision,
    source      text,
    scraped_at  text,
    prev_mid    double precision,
    change_pct  double precision,
    notes       text
);
alter table vula_material_rates enable row level security;

create table if not exists vula_material_rate_log (
    id               bigint generated by default as identity primary key,
    source           text,
    url              text,
    status           text,
    rates_extracted  integer,
    scraped_at       text,
    error            text
);
alter table vula_material_rate_log enable row level security;

create table if not exists vula_takeoff_suppliers (
    id            text primary key,
    tenant_id     text not null default 'default',
    name          text,
    category      text,
    email         text,
    whatsapp      text,
    contact_name  text,
    discount_pct  double precision default 0,
    preferred     boolean default false,
    notes         text,
    updated_at    timestamptz not null default now()
);
alter table vula_takeoff_suppliers enable row level security;

create table if not exists vula_takeoff_orders (
    po_number        text not null,
    tenant_id        text not null default 'default',
    project_name     text,
    supplier_id      text,
    status           text,
    estimated_total  double precision,
    quote_received   double precision default 0,
    sent_at          text,
    lines            jsonb not null default '[]'::jsonb,
    created_at       timestamptz not null default now(),
    primary key (tenant_id, po_number)
);
alter table vula_takeoff_orders enable row level security;

create table if not exists vula_takeoff_jobs (
    id          text primary key,
    tenant_id   text,
    status      text,
    state       jsonb not null default '{}'::jsonb,
    updated_at  timestamptz not null default now()
);
create index if not exists idx_vula_takeoff_jobs_tenant on vula_takeoff_jobs (tenant_id, updated_at desc);
alter table vula_takeoff_jobs enable row level security;
